* *Hunger Makes Me a Modern Girl* - _Carrie Brownstein_
Carrie Brownstein's memoir of the first ~20 years of Sleater-Kinney, and her formative years in
Washington and Oregon.

- It's a slightly disappointing read, because of the remove that's kept between the author and the
  reader when dealing with the most pivotal moments of the band's history. Firing a drummer is given
  short-shrift, as is the final implosion (far more attention is given to CB's ailments and pets
  than really interrogating the reason she blew up the band during The Woods' tour).

- The sense you get is that certain episodes in CB's past are still to painful or uncomfortable - or
  just too personal - to relate to an unknown audience. Throughout the book she writes with
  intensity about the way that music mediates her relationship with her audience; the importance of
  giving it your all while performing, and the degree to which she and the band didn't want to
  settle into anything comfortable. The book treats its readers in the same way: distanced, at arm's
  length and with a certain need-to-know reluctance.

- It's still useful as a partial history of the band (I am ashamed to admit I didn't know that
  Brownstein and Tucker had dated, although that's roughly the extent of the detail you'll find in
  the book about it).
