* *Eleanor Oliphant is Completely Fine*
- TODO

* *Hunger Makes Me a Modern Girl* - _Carrie Brownstein_
- Carrie Brownstein's memoir of the first ~20 years of Sleater-Kinney, and her formative years in
  Washington and Oregon.
- It's a slightly disappointing read, because of the remove that's kept between the author and the
  reader when dealing with the most pivotal moments of the band's history. Firing a drummer is given
  short-shrift, as is the final implosion (far more attention is given to CB's ailments and pets
  than really interrogating the reason she blew up the band during The Woods' tour).
- The sense you get is that certain episodes in CB's past are still to painful or uncomfortable - or
  just too personal - to relate to an unknown audience. Throughout the book she writes with
  intensity about the way that music mediates her relationship with her audience; the importance of
  giving it your all while performing, and the degree to which she and the band didn't want to
  settle into anything comfortable. The book treats its readers in the same way: distanced, at arm's
  length and with a certain need-to-know reluctance.
- It's still useful as a partial history of the band (I am ashamed to admit I didn't know that
  Brownstein and Tucker had dated, although that's roughly the extent of the detail you'll find in
  the book about it).

* *Where'd You Go, Bernadette?*
- TODO

* *Normal People* - _Sally Rooney_
- The story of the relationship between two young people in Ireland. Marianne is the daughter of
  wealthy parents, but has suffered enormous emotional and physical abuse at their hands. Connell is
  the son of their cleaner, and is popular at school. Both are academically gifted.
- They develop a deep relationship at the start of the book, then fate, poor decision making, and
  emotional constipation conspire to move them away from and towards each other like the tides
  coming in and out.
- She is too deeply damaged by her familial abuse to believe that she has worth and therefore
  believes fundamentally that Connell cannot love her; he is unsure of her feelings for him, unable
  to set aside some class anxiety.
- The book is written as, mostly, a series of vignettes separated by periods of time (the chapters
  are 'five weeks later' etc). Some are very affecting (e.g. Marianne with the Swedish photographer
  who treats her roughly in bed; she is revolted when he says he loves her as she views that as
  incompatible with their dynamic, she would be heartbroken to discover that was what love was).
- The protaganists both grow and shrink as they move from school to university. They're
  hyper-articulate, and a little unbelievable capable of acting with maturity in the moment (one of
  them bristles, the other immediately says what they really meant, the issue doesn't linger).
- The book has lovely passages, and is written in such a way that sometimes makes you nearly
  claustrophobic inside their relationship.
- I've heard the book dismissed as 'millenial' or 'for YA'; I don't get that at all - the challenges
  of growing, knowing yourself and building your self-worth, talking frankly about your feelings,
  the pain of a love that you deny yourself are all timeless topics.
